Make Tickets page and Somewhat working Edit Ticket page
MAPReiff/Tikit pull request #21
Opened 2023-04-27 02:05 UTC by Val-Bustamante

Make Ticket page works (interface and functionality). The info button for categories is ugly so I'll make it better lookin down the road. 

Edit Ticket page has an interface and a button in View Ticket that lets you access the page. Actual functionality though does not work yet.

2023-04-27 02:17 UTC, MAPReiff commented on views/editTicket.handlebars
> +</script>
I believe the prof said we can not use inline JS - please move to a dedicated file

2023-04-27 02:21 UTC, MAPReiff requested changes
A few comments left in files, please correct them when you get a chance.

Otherwise looks good.

2023-04-27 02:21 UTC, MAPReiff commented on data/tickets.js
> +  console.log(priority);
Please remove unnecessary console.logs

2023-04-27 02:21 UTC, MAPReiff commented on public/js/makeTicket.js
> +    console.log("wow");
Please remove unnecessary console.logs

2023-04-27 02:21 UTC, MAPReiff commented on routes/tickets.js
> +    console.log("IN MAKE TICKET POST")
Please remove unnecessary console.logs

2023-04-27 02:21 UTC, MAPReiff commented on routes/tickets.js
> +            console.log("ticketId",createdTicket._id);
Please remove unnecessary console.logs

2023-04-27 22:16 UTC, MAPReiff commented
@Val-Bustamante bumping this regarding the comment on the script in `editTicket.handlebars`

2023-04-29 20:51 UTC, MAPReiff approved these changes

2023-04-30 01:03 UTC, bigguyhere commented on routes/tickets.js
> +      ticket = await ticketData.get(req.params.id);
Ticket is assigned a value, but never used

2023-04-30 01:03 UTC, bigguyhere commented on routes/tickets.js
> +      user = await userData.get(req.session.user._id);
User is assigned a value, but never used

2023-05-01 21:05 UTC, merged